-- Allgemeines Kontaktformular (MP 6.3).
CREATE TABLE contact_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    anliegen VARCHAR(50) NOT NULL,
    name VARCHAR(150) NULL,
    email VARCHAR(254) NOT NULL,
    telefon VARCHAR(40) NULL,
    nachricht TEXT NULL,
    region VARCHAR(100) NULL,
    consent_text_version VARCHAR(40) NULL,
    consent_at DATETIME NULL COMMENT 'UTC',
    status ENUM('neu', 'in_bearbeitung', 'erledigt', 'spam') NOT NULL DEFAULT 'neu',
    source VARCHAR(50) NULL,
    utm_source VARCHAR(150) NULL,
    utm_medium VARCHAR(150) NULL,
    utm_campaign VARCHAR(150) NULL,
    utm_term VARCHAR(150) NULL,
    utm_content VARCHAR(150) NULL,
    landing_page VARCHAR(255) NULL,
    referrer VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC',
    PRIMARY KEY (id),
    UNIQUE KEY uq_contact_requests_uuid (uuid),
    KEY idx_contact_requests_status (status, created_at),
    KEY idx_contact_requests_anliegen (anliegen, created_at),
    KEY idx_contact_requests_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
