<?php

declare(strict_types=1);

/*
 * Metadaten je Seite. Schlüssel = Seitenschlüssel (Template pages/{schluessel}.html.twig).
 *
 * pfad         URL der Seite (mit abschließendem Schrägstrich)
 * titel        Kurzbezeichnung (Überschrift, Breadcrumb, OG-Bild)
 * seitentitel  Inhalt des title-Elements
 * beschreibung Meta-Beschreibung, sachlich, bis etwa 160 Zeichen
 * eltern       Seitenschlüssel der übergeordneten Seite für Breadcrumbs (null = direkt unter Start)
 * schema       schema.org-Typ der Seite (Service, WebPage, AboutPage, ContactPage, CollectionPage, none)
 * sitemap      in sitemap.xml aufnehmen
 * og           Open-Graph-Bild erzeugen (Standard true)
 */
return [
    'start' => [
        'pfad' => '/',
        'titel' => 'Start',
        'seitentitel' => 'Hausverwaltung Müller GmbH | WEG- und Mietverwaltung Monheim',
        'beschreibung' => 'Hausverwaltung Müller GmbH aus Monheim am Rhein: WEG-Verwaltung, Mietverwaltung und Sondereigentumsverwaltung seit 2020. Angebot unverbindlich anfordern.',
        'eltern' => null,
        'schema' => 'WebPage',
        'sitemap' => true,
    ],
    'weg-verwaltung' => [
        'pfad' => '/weg-verwaltung/',
        'titel' => 'WEG-Verwaltung',
        'seitentitel' => 'WEG-Verwaltung | Hausverwaltung Müller GmbH',
        'beschreibung' => 'WEG-Verwaltung durch die Hausverwaltung Müller GmbH: Leistungsumfang, Abgrenzung und Ablauf für Wohnungseigentümergemeinschaften und Beiräte.',
        'eltern' => null,
        'schema' => 'Service',
        'sitemap' => true,
    ],
    'mietverwaltung' => [
        'pfad' => '/mietverwaltung/',
        'titel' => 'Mietverwaltung',
        'seitentitel' => 'Mietverwaltung | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Mietverwaltung für Vermieter und Investoren: Leistungsumfang und Ablauf bei der Hausverwaltung Müller GmbH.',
        'eltern' => null,
        'schema' => 'Service',
        'sitemap' => true,
    ],
    'se-verwaltung' => [
        'pfad' => '/se-verwaltung/',
        'titel' => 'SE-Verwaltung',
        'seitentitel' => 'Sondereigentumsverwaltung | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Sondereigentumsverwaltung für Kapitalanleger: Betreuung vermieteter Eigentumswohnungen durch die Hausverwaltung Müller GmbH.',
        'eltern' => null,
        'schema' => 'Service',
        'sitemap' => true,
    ],
    'asset-management' => [
        // Entwurf: Leistung durch die Geschäftsführung zu bestätigen (docs/wissen-inhaltsplan.md Abschnitt 4).
        'pfad' => '/asset-management/',
        'titel' => 'Asset Management',
        'seitentitel' => 'Asset Management | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Asset Management für Wohnimmobilien: Bestandsanalyse, Objektstrategie, Investitionsplanung und Berichtswesen für Kapitalanleger und Eigentümer mehrerer Objekte.',
        'eltern' => null,
        'schema' => 'Service',
        'sitemap' => true,
    ],
    'verwalterwechsel' => [
        'pfad' => '/verwalterwechsel/',
        'titel' => 'Verwalterwechsel',
        'seitentitel' => 'Verwalterwechsel für WEG | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Verwalterwechsel für Wohnungseigentümergemeinschaften: Ablauf, Zeitplan, Beschlussfassung und Unterlagenübergabe beim Wechsel zur Hausverwaltung Müller GmbH.',
        'eltern' => null,
        'schema' => 'Service',
        'sitemap' => true,
    ],
    'vermietung' => [
        'pfad' => '/vermietung/',
        'titel' => 'Vermietung',
        'seitentitel' => 'Vermietung | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Vermietung Ihrer Immobilie durch die Hausverwaltung Müller GmbH: Leistung für Eigentümer von der Vermarktung bis zur Übergabe.',
        'eltern' => null,
        'schema' => 'Service',
        'sitemap' => true,
    ],
    'verkauf' => [
        'pfad' => '/verkauf/',
        'titel' => 'Verkauf',
        'seitentitel' => 'Immobilie verkaufen | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Verkauf Ihrer Immobilie mit der Hausverwaltung Müller GmbH: Marktwerteinschätzung, Vermarktung, Besichtigungen und Begleitung bis zum Notartermin.',
        'eltern' => null,
        'schema' => 'Service',
        'sitemap' => true,
    ],
    'wertgutachten' => [
        'pfad' => '/wertgutachten/',
        'titel' => 'Wertgutachten',
        'seitentitel' => 'Wertgutachten | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Wertermittlung für Immobilien: Marktwerteinschätzung der Hausverwaltung Müller GmbH, Abgrenzung zum Sachverständigengutachten, Anlässe und Ablauf.',
        'eltern' => null,
        'schema' => 'Service',
        'sitemap' => true,
    ],
    'wissen' => [
        'pfad' => '/wissen/',
        'titel' => 'Wissen und FAQ',
        'seitentitel' => 'Wissen und FAQ | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Wissen und FAQ zur Immobilienverwaltung für Wohnungseigentümer, Beiräte, Vermieter und Mieter. Allgemeine Informationen, keine Rechtsberatung.',
        'eltern' => null,
        'schema' => 'CollectionPage',
        'sitemap' => true,
    ],
    'wissen-artikel' => [
        // Dynamische Seite (Route /wissen/{slug}/, config/routes/wissen.php). Titel, Beschreibung
        // und Schema kommen je Artikel aus WissenController über PageMeta::build()-Overrides.
        'pfad' => '/wissen/',
        'titel' => 'Wissensbeitrag',
        'eltern' => 'wissen',
        'schema' => 'none',
        'sitemap' => false,
        'og' => false,
    ],
    'betreuungsgebiete' => [
        'pfad' => '/betreuungsgebiete/',
        'titel' => 'Betreuungsgebiete',
        'seitentitel' => 'Betreuungsgebiete | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Betreuungsgebiete der Hausverwaltung Müller GmbH mit Hauptsitz in Monheim am Rhein. Übersicht der Regionen mit Angabe der Betreuungsform.',
        'eltern' => null,
        'schema' => 'WebPage',
        'sitemap' => true,
    ],
    'referenzen' => [
        'pfad' => '/referenzen/',
        'titel' => 'Referenzen',
        'seitentitel' => 'Referenzen | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Referenzen der Hausverwaltung Müller GmbH: verwaltete Objekttypen und Fallbeispiele, veröffentlicht mit Freigabe der Eigentümer.',
        'eltern' => null,
        'schema' => 'CollectionPage',
        'sitemap' => true,
    ],
    'ueber-uns' => [
        'pfad' => '/ueber-uns/',
        'titel' => 'Über uns',
        'seitentitel' => 'Über uns | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Die Hausverwaltung Müller GmbH verwaltet seit 2020 Wohnungseigentum und Mietobjekte. Unternehmensdaten, Bestand, Mitgliedschaften und Arbeitsweise.',
        'eltern' => null,
        'schema' => 'AboutPage',
        'sitemap' => true,
    ],
    'fakten' => [
        // Zitierfähige Faktenseite (GEO, docs/seo-geo.md). Inhalte ausschließlich aus config/unternehmen.php,
        // config/kennzahlen.php, config/fakten.php und docs/auftraggeber-angaben.md.
        'pfad' => '/fakten/',
        'titel' => 'Die HVM in Zahlen und Fakten',
        'seitentitel' => 'Die HVM in Zahlen und Fakten | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Hausverwaltung Müller GmbH in Zahlen: Sitz, Register, Gründung 2020, Bestand mit Stichtag, Mitgliedschaften, Leistungen und bestätigte Merkmale.',
        'eltern' => 'ueber-uns',
        'schema' => 'AboutPage',
        'sitemap' => true,
    ],
    'karriere' => [
        'pfad' => '/karriere/',
        'titel' => 'Karriere',
        'seitentitel' => 'Karriere | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Karriere bei der Hausverwaltung Müller GmbH in Monheim am Rhein: Stellenangebote und Bewerbung, auch ohne ausgeschriebene Stelle.',
        'eltern' => null,
        'schema' => 'WebPage',
        'sitemap' => true,
    ],
    'karriere-bewerbung' => [
        'pfad' => '/karriere/bewerbung/',
        'titel' => 'Bewerbung',
        'seitentitel' => 'Bewerbung | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Bewerbungsunterlagen online an die Hausverwaltung Müller GmbH übermitteln.',
        'eltern' => 'karriere',
        'schema' => 'WebPage',
        'sitemap' => true,
    ],
    'bewerbung-danke' => [
        'pfad' => '/karriere/bewerbung/danke/',
        'titel' => 'Vielen Dank',
        'seitentitel' => 'Bewerbung eingegangen | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Ihre Bewerbung ist bei der Hausverwaltung Müller GmbH eingegangen.',
        'eltern' => 'karriere-bewerbung',
        'schema' => 'none',
        'sitemap' => false,
        'og' => false,
    ],
    'service' => [
        'pfad' => '/service/',
        'titel' => 'Service für Mieter und Eigentümer',
        'seitentitel' => 'Service für Mieter und Eigentümer | Hausverwaltung Müller',
        'beschreibung' => 'Service für Mieter und Eigentümer: Portal, Schadensmeldung, Notfall, Formulare und Erreichbarkeit der Hausverwaltung Müller GmbH.',
        'eltern' => null,
        'schema' => 'WebPage',
        'sitemap' => true,
    ],
    'notfall' => [
        'pfad' => '/notfall/',
        'titel' => 'Notfall',
        'seitentitel' => 'Notfall im Objekt | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Notfall im Objekt: wann ein Notfall vorliegt, wann nicht, und wie Sie die Hausverwaltung Müller GmbH erreichen.',
        'eltern' => 'service',
        'schema' => 'WebPage',
        'sitemap' => true,
    ],
    'kontakt' => [
        'pfad' => '/kontakt/',
        'titel' => 'Kontakt',
        'seitentitel' => 'Kontakt | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Kontakt zur Hausverwaltung Müller GmbH, Rheinpromenade 13, 40789 Monheim am Rhein. Nachricht über das Kontaktformular senden.',
        'eltern' => null,
        'schema' => 'ContactPage',
        'sitemap' => true,
    ],
    'angebot' => [
        'pfad' => '/angebot/',
        'titel' => 'Angebot anfordern',
        'seitentitel' => 'Angebot anfordern | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Unverbindliches Angebot für WEG-Verwaltung, Mietverwaltung oder SE-Verwaltung anfordern. Anfrage in wenigen Schritten.',
        'eltern' => null,
        'schema' => 'WebPage',
        'sitemap' => true,
    ],
    'angebot-danke' => [
        'pfad' => '/angebot/danke/',
        'titel' => 'Vielen Dank',
        'seitentitel' => 'Anfrage eingegangen | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Ihre Anfrage ist bei der Hausverwaltung Müller GmbH eingegangen. Die nächsten Schritte im Überblick.',
        'eltern' => 'angebot',
        'schema' => 'none',
        'sitemap' => false,
        'og' => false,
    ],
    'kontakt-danke' => [
        'pfad' => '/kontakt/danke/',
        'titel' => 'Vielen Dank',
        'seitentitel' => 'Nachricht eingegangen | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Ihre Nachricht ist bei der Hausverwaltung Müller GmbH eingegangen.',
        'eltern' => 'kontakt',
        'schema' => 'none',
        'sitemap' => false,
        'og' => false,
    ],
    'impressum' => [
        'pfad' => '/impressum/',
        'titel' => 'Impressum',
        'seitentitel' => 'Impressum | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Impressum der Hausverwaltung Müller GmbH, Monheim am Rhein: Anbieterangaben, Registereintrag und Kontakt.',
        'eltern' => null,
        'schema' => 'WebPage',
        'sitemap' => true,
    ],
    'datenschutz' => [
        'pfad' => '/datenschutz/',
        'titel' => 'Datenschutzerklärung',
        'seitentitel' => 'Datenschutzerklärung | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Datenschutzerklärung der Hausverwaltung Müller GmbH: Verarbeitung personenbezogener Daten auf muellerhv.de, Formulare, Speicherdauer und Ihre Rechte.',
        'eltern' => null,
        'schema' => 'WebPage',
        'sitemap' => true,
    ],
    'barrierefreiheit' => [
        'pfad' => '/barrierefreiheit/',
        'titel' => 'Erklärung zur Barrierefreiheit',
        'seitentitel' => 'Erklärung zur Barrierefreiheit | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Erklärung zur Barrierefreiheit der Webseite der Hausverwaltung Müller GmbH: Ziel WCAG 2.2 AA, bekannte Einschränkungen und Kontakt für Rückmeldungen.',
        'eltern' => null,
        'schema' => 'WebPage',
        'sitemap' => true,
    ],
    'styleguide' => [
        'pfad' => '/styleguide/',
        'titel' => 'Styleguide',
        'seitentitel' => 'Styleguide (intern) | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Interner Styleguide des Designsystems, nur außerhalb der Produktion erreichbar.',
        'eltern' => null,
        'schema' => 'none',
        'sitemap' => false,
        'og' => false,
    ],
    'admin' => [
        'pfad' => '/admin/',
        'titel' => 'Verwaltung',
        'seitentitel' => 'Verwaltung (intern) | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Interner Bereich.',
        'eltern' => null,
        'schema' => 'none',
        'sitemap' => false,
        'og' => false,
    ],
    '404' => [
        'pfad' => '/404/',
        'titel' => 'Seite nicht gefunden',
        'seitentitel' => 'Seite nicht gefunden | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Die angeforderte Seite wurde nicht gefunden.',
        'eltern' => null,
        'schema' => 'none',
        'sitemap' => false,
        'og' => false,
    ],
    '500' => [
        'pfad' => '/500/',
        'titel' => 'Vorübergehende Störung',
        'seitentitel' => 'Vorübergehende Störung | Hausverwaltung Müller GmbH',
        'beschreibung' => 'Die Seite kann derzeit nicht angezeigt werden.',
        'eltern' => null,
        'schema' => 'none',
        'sitemap' => false,
        'og' => false,
    ],
];
